services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - temp_data:/app/temp
      - cache_data:/app/cache
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  temp_data:
  cache_data:
  redis_data:
